### ISSUE TITLE
New `gpat_txt2grid` function

### ISSUE THREAD

**Issue by Nowosad** [Nowosad/geopat2#27]

**Comment by StefanStamenkovic** [comment]
Hello, I've found this subject 'gpat_txt2grid function' so I wanted to check does this function really exists and where can I read some article about it? Also, is there any example with gpat_polygon function?

**Comment by Nowosad** [comment]
Hi,
the gpat_txt2grid module still does not exist. Is there any reason you are interested in this module?

Regarding to the gpat_polygon function - you can find some examples of its use in this presentation https://nowosad.github.io/geostat18/geostat18_nowosad (slides 69-70), GeoPAT2 manual (page 49), and the GeoPAT2 blog series - https://nowosad.github.io/post/geopat-2-extend/.

**Comment by StefanStamenkovic** [comment]
Actually I'm just looking for a proper way to use geopat_polygon function, and seems that I do not understand how does it work. I believe this isn't right theme to post this kind of question so you can redirect me to right place. :) This is how I wanted to use it:

gpat_gridhis -i April.tif -o apr_grid -s cooc -z 10 -f 10 -n pdf
gpat_polygon -i April.tif -e raster.tif -o raster_sig.txt -s cooc -n pdf
gpat_search -i apr_grid -r raster_sig.txt

April.tif is raster layer with data, and raster.tif contains polygons of interest. This process eventually comes to an end without errors but there is no any output after gpat_search command, even if it shows that calculation is over. I guess I'm doing something wrong with gpat_polygon but since there is no any completed examples as for gpat_search (Manual 31-32) I'm not sure what is it. Any suggestions?

**Comment by Nowosad** [comment]
Hi Stefan,
great question. Truth to be told - I've never used the search module on a gpat_polygon output. 
I tried it today and it worked well on my data. Can you provide me the data you are using? Either here or by the email?
I will also try to add a polygon example to the GeoPAT 2 manual sometime next week.
